<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>RoweMod.Play</AssemblyName>
    <RootNamespace>RoweMod.Play</RootNamespace>
    <Product>RoweMod Play</Product>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RoweMod.Core\RoweMod.Core.csproj" />
    <ProjectReference Include="..\DtPatcher\DtPatcher.csproj" />
  </ItemGroup>
</Project>
